#Use nginx base image
FROM nginx:alpine

#Copy the HTML file into the docker image being built
COPY index.html /usr/share/nginx/html/index.html
COPY protocols.conf /etc/nginx/conf.d/default.conf

COPY nginx /security/nginx/

# Expose the port 80 for remote access
EXPOSE 80
EXPOSE 443

# Command to be executed
CMD ["nginx", "-g", "daemon off;"]