apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  dex.github.clientID: Ov23litoeqgMyAMQ8G8P
  dex.github.clientSecret: dd09074b6f8bda6f828e335919e2082a2b0bdec7
