apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mysql-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mysql-db 
  minReplicas: 1  
  maxReplicas: 10  
  targetCPUUtilizationPercentage: 50  # Target average CPU utilization 
