apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-mysql
  template:
    metadata:
      labels:
        app: spring-mysql
    spec:
      containers:
      - name: spring-mysql
        image: spring-mysql:v14
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: spring-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_JPA_DATABASE_PLATFORM
          valueFrom:
            configMapKeyRef:
              name: spring-config
              key: SPRING_JPA_DATABASE_PLATFORM
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: spring-secret
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: spring-secret
              key: SPRING_DATASOURCE_PASSWORD
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"          
          limits:
            cpu: "500m"
            memory: "1024Mi"
