apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spring-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-mysql  
  minReplicas: 1  
  maxReplicas: 10  
  targetCPUUtilizationPercentage: 50  # Target average CPU utilization 
