apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/demodb
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
