version: '3.8'

services:
  site1:
    image: site1:v1
    container_name: site1
    ports:
      - "8081:80"

  site2:
    image: site2:v1
    container_name: site2
    ports:
      - "8082:80"

  haproxy:
    image: haproxy:2.2
    container_name: haproxy2
    user: root
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    ports:
      - "443:443"
      - "8084:8084"
