app:
  datasource:
    jdbc-url: jdbc:postgresql://postgres:5432/demodb
    username: postgres
    password: Branajay
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
