version: '3'
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - nexus-data:/nexus-data
    environment:
      - NEXUS_CONTEXT=
    restart: unless-stopped

volumes:
  nexus-data:
    driver: local
