version: '3.8'

services:
  spring-mysql:
    image: spring-mysql:v9
    container_name: spring-mysql
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: Branajay
      MYSQL_PORT: 3306 
    depends_on:
      - mysql-db
    networks:
      - app-network

  mysql-db:
    image: mysql:8.0.37
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Branajay
      MYSQL_DATABASE: demodb
      MYSQL_PASSWORD: Branajay
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
